#!/bin/sh
# Take a durable copy of this repository, tracker reasoning included.
#
#     sh data-raw/backup.sh                 # refresh, commit, bundle, mirror, publish
#     sh data-raw/backup.sh --no-commit     # refuse rather than commit a stale snapshot
#     sh data-raw/backup.sh <bundle-path>   # write the bundle somewhere specific
#
# Why this exists. `.fp/` is gitignored, so the issue tracker is a local
# database that no commit, no clone and no bundle has ever contained, while the
# committed docs cite `SITE-*` ids as the evidence behind their decisions.
# `data-raw/snapshot-tracker.sh` writes the only copy that is in git. Running a
# backup without refreshing it first produces an artifact that carries a stale
# copy of the only tracker reasoning in git -- and looks current, which is worse
# than having no snapshot at all.
#
# Until this script existed that ordering was enforced by a paragraph in
# docs/repo-hygiene.md. Here it is enforced by control flow: nothing is copied
# anywhere until the snapshot is regenerated and committed.
#
# THE COMMIT IS THE POINT. A mirror push copies commits and a bundle packs refs;
# neither one can see an uncommitted working tree. Refreshing the snapshot
# without committing it therefore produces exactly the stale artifact this
# script exists to prevent, so a changed snapshot is committed before any copy
# is taken. Only `docs/tracker-snapshot.md` is committed, by pathspec, so
# unrelated staged work is left alone. Pass --no-commit to abort instead.
#
# NO NETWORK REQUIRED. The `backup` remote is a local path
# (~/Projects/_backups/sitemapr.git) and the bundle is a local file, so a full
# backup succeeds while the GitHub remote is unreachable -- which it has been
# since the account suspension, and which is precisely when having a copy
# matters most.
set -eu

SNAPSHOT="docs/tracker-snapshot.md"
MIRROR_REMOTE="backup"
ORIGIN_REMOTE="origin"

commit_snapshot=1
bundle_path=""
snapshot_commit=""

for arg in "$@"; do
	case "$arg" in
	--no-commit) commit_snapshot=0 ;;
	-*)
		echo "unknown option: $arg" >&2
		exit 2
		;;
	*) bundle_path="$arg" ;;
	esac
done

if [ ! -d .git ]; then
	echo "no .git here; run this from the repository root" >&2
	exit 1
fi

# ---------------------------------------------------------------- 1. refresh

echo "==> refreshing $SNAPSHOT"
sh data-raw/snapshot-tracker.sh

# `git diff --quiet` exits 1 when the path differs from HEAD. Under `set -e` a
# bare call would abort the script on the very case we care about, so the status
# is captured rather than inherited.
snapshot_dirty=0
git diff --quiet -- "$SNAPSHOT" || snapshot_dirty=1

if [ "$snapshot_dirty" -eq 1 ]; then
	if [ "$commit_snapshot" -eq 0 ]; then
		echo "$SNAPSHOT changed and --no-commit was given." >&2
		echo "Commit it, then re-run: any copy taken now would be stale." >&2
		exit 1
	fi
	echo "==> committing the refreshed snapshot"
	git commit --only "$SNAPSHOT" -q -m "chore: refresh the tracker snapshot

Generated by data-raw/backup.sh before taking a copy. The tracker itself
lives in gitignored .fp/, so this file is the only copy of the reasoning
behind the SITE-* ids the docs cite."
	snapshot_commit=$(git rev-parse HEAD)
else
	echo "==> snapshot already current, nothing to commit"
fi

# ----------------------------------------------------------------- 2. bundle

if [ -z "$bundle_path" ]; then
	stamp=$(date +%Y%m%d-%H%M%S)
	bundle_dir="$HOME/Projects/_backups"
	bundle_path="$bundle_dir/sitemapr-$stamp.bundle"
fi

mkdir -p "$(dirname "$bundle_path")"

echo "==> writing $bundle_path"
git bundle create "$bundle_path" --all

# A bundle that does not verify is not a backup. Checking now means the failure
# surfaces here rather than on the machine that needs to restore from it.
echo "==> verifying the bundle"
git bundle verify "$bundle_path" >/dev/null

echo "wrote $bundle_path ($(wc -c <"$bundle_path" | tr -d ' ') bytes)"

# ----------------------------------------------------------------- 3. mirror
#
# The bundle is written FIRST, and deliberately. On the first real run of this
# script the mirror push failed and `set -e` killed the script before the bundle
# step, so a backup run that reported an error produced no archive at all --
# the one outcome a backup must never have. The local, network-free half now
# completes before anything that can fail remotely is attempted, and a mirror
# failure is reported at the end instead of aborting.
#
# --mirror makes the remote match this repository exactly, which means a ref
# deleted here is deleted there on the next run. That is the intended meaning of
# a mirror and what docs/repo-hygiene.md has always described, but it also means
# the mirror alone is not an archive: it cannot recover a branch deleted before
# the last run. The bundle above is the archive half.

mirror_failed=0

if git remote get-url "$MIRROR_REMOTE" >/dev/null 2>&1; then
	echo "==> mirroring to $MIRROR_REMOTE ($(git remote get-url "$MIRROR_REMOTE"))"
	# --no-verify skips the pre-push verify gate on purpose. That gate runs
	# `R CMD check` and takes minutes, but the deeper reason is that gating a
	# backup on a green tree is backwards: a broken tree is exactly when the
	# copy matters, and a lint failure must never be able to stop one.
	git push --mirror --no-verify "$MIRROR_REMOTE" || mirror_failed=1
else
	echo "==> no '$MIRROR_REMOTE' remote configured, skipping the mirror" >&2
fi

# ---------------------------------------------------------------- 4. publish
#
# The snapshot commit is otherwise stranded: run this on main and it sits
# unpushed, so the next merge leaves local and origin diverged over a generated
# file, long after the run that caused it.
#
# Pushing it through the pre-push gate costs ~200s and buys provably nothing.
# `^docs$` is in .Rbuildignore, so R CMD check never sees this file; the docs
# stage reads man/ + NAMESPACE, registry reads docs/findings-registry.csv, and
# lint reads R/. No stage of the gate can observe it.
#
# THE EXEMPTION IS BOUNDED ON PURPOSE. A bare `git push --no-verify` would carry
# out every other unpushed commit ungated too -- real code riding out on the
# back of a snapshot refresh. So the push happens only when the snapshot commit
# is the single unpushed commit and is exactly the one made above. Anything else
# leaves it for a normal push to carry through the gate.
#
# HOW THE GUARD IS TESTED, and not in place. Copy this script into a throwaway
# repository whose `origin` and `backup` are local bare repos, stub
# data-raw/snapshot-tracker.sh to rewrite the snapshot file, and drive the five
# states from there. It has to be a separate repository: this one sets
# fetch.prune=true and something in the environment runs `git fetch --all`, so a
# hand-made refs/remotes/origin/* fixture is deleted before the code can read
# it. Running the real file elsewhere beats adding a seam to it here.
#
# Detached HEAD refuses like the other two refusal states, but the commit was
# already made by then. It lands in this run's bundle (`--all` includes HEAD),
# never reaches the mirror (--mirror pushes refs/* and it is under no ref), and
# is orphaned by the next checkout -- after which the following run from a
# branch re-detects the snapshot as dirty and commits it properly.

publish_failed=0

if [ -n "$snapshot_commit" ] && git remote get-url "$ORIGIN_REMOTE" >/dev/null 2>&1; then
	branch=$(git symbolic-ref --quiet --short HEAD || echo "")
	upstream="$ORIGIN_REMOTE/$branch"

	if [ -z "$branch" ]; then
		echo "==> detached HEAD, leaving the snapshot commit unpushed"
	elif ! git rev-parse --verify --quiet "$upstream" >/dev/null; then
		echo "==> no $upstream ref, leaving the snapshot commit unpushed"
	else
		# A stale $upstream can only inflate this count, so staleness makes the
		# check refuse rather than over-permit. A genuinely diverged origin is
		# caught by the push itself, which is non-fast-forward and non-fatal.
		ahead=$(git rev-list --count "$upstream..HEAD")
		if [ "$ahead" = "1" ] && [ "$(git rev-parse HEAD)" = "$snapshot_commit" ]; then
			echo "==> publishing the snapshot commit to $upstream"
			git push --no-verify "$ORIGIN_REMOTE" "$branch" || publish_failed=1
		else
			echo "==> $ahead unpushed commit(s) on $branch, so the snapshot"
			echo "    commit is not pushed. A normal push will carry it"
			echo "    through the verify gate with the rest."
		fi
	fi
fi

if [ "$mirror_failed" -eq 1 ] || [ "$publish_failed" -eq 1 ]; then
	echo >&2
	[ "$mirror_failed" -eq 1 ] && echo "MIRROR FAILED." >&2
	[ "$publish_failed" -eq 1 ] && echo "PUBLISH FAILED (snapshot commit is local only)." >&2
	echo "The bundle above is complete and verified, so the repository is" >&2
	echo "backed up; only the remote copies need attention." >&2
	exit 1
fi

echo "backed up: $bundle_path"
