#!/bin/sh
# Snapshot the fp issue tracker into a committed markdown file.
#
#     sh data-raw/snapshot-tracker.sh
#
# Why this exists. `.fp/` is gitignored (and .Rbuildignore carries ^\.fp$ so it
# never reaches R CMD check either), so the tracker is a local SQLite database
# that no commit, no bundle and no clone has ever contained. That is a problem
# specific to projects built this way rather than a general one: the committed
# design docs cite issue ids as the evidence behind their decisions -- in raddr,
# section 10's open-items table alone names more than twenty -- and the
# reasoning those ids point at lives in issue comments, not in code. Lose .fp/
# and every one of those citations dangles while the code survives intact.
#
# The same gap was found from the outside first: raddr's O12 row records that a
# sibling repository's .fp/ is gitignored too, which is why a report filed there
# exists in no git history anywhere. This script is that finding applied to
# whichever repository it is run in.
#
# It is deliberately a snapshot and not a sync. fp stays the working tracker --
# nothing here is meant to be read in preference to `fp context <id>`, and
# nothing reads this file back. It exists so the narrative survives the disk.
#
# GENERATED OUTPUT, OVERWRITTEN WHOLESALE. Hand-edits to the output file are
# lost on the next run. This is the hazard raddr's open item O10 turned up with
# inst/NOTICE, where build-registry.R silently deleted an appended license
# notice, so the output carries the same warning in its own header.
#
# Issues are emitted in sorted short-id order rather than tree or creation
# order, so that regenerating produces a minimal diff: a new comment changes one
# stanza instead of reshuffling the file.
#
# PORTABLE ACROSS REPOSITORIES. The issue-id prefix is read out of
# .fp/config.toml and never guessed: it is not a transform of the directory name
# (sitemapr's prefix is SITE, robotstxtr's is ROBO), and
# `fp issue list --format json` reports bare short ids with no prefix field at
# all, so the config file is the only authority for it. The three assignments
# below are the only per-repository settings; the rest of the script is
# identical in every copy.
set -eu

# Where the snapshot is written, relative to the repository root.
OUT="docs/tracker-snapshot.md"

# What the snapshot is a backstop for: the committed docs in this repository
# that cite issue ids. Named in the output header so a reader arriving at the
# file knows why it is in git at all.
CITED_BY="\`docs/architecture.md\` and the other docs under \`docs/\`"

# Optional. A local precedent for "generated file, overwritten wholesale",
# named in the output header to make the hazard concrete. It is punctuated as a
# trailing clause; leave it empty in a repository that has no such precedent.
PRECEDENT=""

if ! command -v fp >/dev/null 2>&1; then
	echo "fp not found on PATH; cannot snapshot the tracker" >&2
	exit 1
fi

if [ ! -d .fp ]; then
	echo "no .fp/ directory here; run this from the repository root" >&2
	exit 1
fi

if [ ! -f .fp/config.toml ]; then
	echo ".fp/config.toml is missing; cannot read the issue-id prefix" >&2
	exit 1
fi

# The prefix `fp context` wants in front of a short id. Read, not guessed: see
# the header note above for why neither the directory name nor the JSON listing
# can stand in for this.
prefix=$(sed -n 's/^[[:space:]]*prefix[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' .fp/config.toml | head -n 1)

if [ -z "$prefix" ]; then
	echo "no prefix key in .fp/config.toml; cannot build issue ids" >&2
	exit 1
fi

# Short ids, sorted, so the output order is stable across runs.
ids=$(fp issue list --format json | python3 -c '
import json, sys
d = json.load(sys.stdin)
for s in sorted(i["shortId"] for i in d["issues"]):
    print(s)
')

count=$(printf "%s\n" "$ids" | grep -c .)

{
	echo "# fp tracker snapshot"
	echo
	echo "**Generated by \`data-raw/snapshot-tracker.sh\` on $(date +%Y-%m-%d).**"
	echo "$count issues. Do not hand-edit: the next run overwrites this file"
	echo "wholesale$PRECEDENT."
	echo
	echo "\`.fp/\` is gitignored, so this file is the only copy of the tracker in"
	echo "git. It is a backstop for the $prefix-* citations in"
	echo "$CITED_BY, not a replacement for the tracker: \`fp\` remains"
	echo "authoritative and \`fp context <id>\` remains the way to read an issue."
	echo
	echo "## Hierarchy"
	echo
	echo '```'
	# Strip trailing spaces and tabs here too. The fence makes this a code
	# block, but the pre-commit trailing-whitespace hook is not markdown-aware
	# and strips inside fences as well, so leaving them in would be the same
	# instability described at the per-issue loop below.
	fp tree | sed 's/[[:blank:]]*$//'
	echo '```'
	echo
	echo "## Issues"
	echo
	echo "$count stanzas, in sorted short-id order. Each is \`fp context\` output"
	echo "with its headings demoted one level."
	echo

	for s in $ids; do
		# Demote every ATX heading one level so the per-issue h1 becomes an h2
		# and nests under "## Issues" instead of competing with the title.
		#
		# Strip trailing spaces and tabs in the same pass. Issue bodies carry
		# them -- a soft-wrapped line that broke mid-sentence, a paragraph
		# typed with one space too many -- and the pre-commit
		# trailing-whitespace hook rewrites them out at commit time. The
		# committed bytes would then stop matching what this script emits, so
		# the snapshot could never look clean twice in a row. That is the same
		# failure the end-of-file-fixer collapse below prevents, for a
		# different hook, and it belongs here in the emitter rather than being
		# patched per repository.
		fp context "$prefix-$s" | sed -e 's/^#/##/' -e 's/[[:blank:]]*$//'
		echo
	done
} >"$OUT.tmp"

# Collapse the trailing blank lines the per-issue loop leaves behind. Without
# this the pre-commit end-of-file-fixer rewrites the file after it is generated,
# so the next run would report a diff against a tree that was already committed
# and the snapshot would never look clean twice in a row.
python3 -c '
import sys
p = sys.argv[1]
with open(p, encoding="utf-8") as f:
    text = f.read()
with open(p, "w", encoding="utf-8") as f:
    f.write(text.rstrip("\n") + "\n")
' "$OUT.tmp"

mv "$OUT.tmp" "$OUT"

echo "wrote $OUT ($count issues, $(wc -c <"$OUT" | tr -d ' ') bytes)"
