# Byte-level format sniffer unit tests (Layer B + fetch_classification.feature
# sniff scenarios). Internal fns are referenced via sitemapr:::.
#
# Inputs are built as raw vectors: charToRaw() for text/markup, as.raw() for
# fixed magic bytes, gzfile()+writeBin() for real gzip-container bytes (NB:
# memCompress(., "gzip") emits a raw zlib stream "78 9c", NOT a gzip container
# with the 1f 8b magic, so it cannot be used to exercise the sniffer), and a
# synthesized 512-byte block with "ustar" at offset 257 for an uncompressed tar.

sniff <- function(x) sitemapr:::sniff_format(x)

# Produce real gzip-container bytes (leading magic 1f 8b) for a raw payload.
gzip_bytes <- function(payload) {
  tf <- tempfile()
  on.exit(unlink(tf), add = TRUE)
  con <- gzfile(tf, "wb")
  writeBin(payload, con)
  close(con)
  readBin(tf, what = "raw", n = file.info(tf)$size)
}

# Build a minimal but valid uncompressed POSIX tar header block: 512 zero bytes
# with the ASCII magic "ustar" placed at offset 257 (0-based).
make_tar_header <- function() {
  block <- raw(512L)
  block[258:262] <- charToRaw("ustar")
  block
}

# ---- empty -------------------------------------------------------------------

test_that("zero-length raw is empty", {
  expect_identical(sniff(raw(0L)), "empty")
})

test_that("NULL is empty", {
  expect_identical(sniff(NULL), "empty")
})

test_that("whitespace-only content is text, not empty", {
  expect_identical(sniff(charToRaw("   \n\t  \r\n")), "text")
})

# ---- gzip --------------------------------------------------------------------

test_that("gzip magic bytes classify as gzip", {
  expect_identical(sniff(as.raw(c(0x1F, 0x8B, 0x08, 0x00))), "gzip")
})

test_that("real gzip-compressed XML classifies as gzip (feature scenario)", {
  xml <- '<?xml version="1.0"?><urlset><url><loc>http://a/</loc></url></urlset>'
  gz <- gzip_bytes(charToRaw(xml))
  expect_identical(sniff(gz), "gzip")
})

test_that("a gzip-wrapped tar (.tar.gz) sniffs as gzip, not tar", {
  payload <- as.raw(c(make_tar_header(), make_tar_header()))
  gz <- gzip_bytes(payload)
  expect_identical(sniff(gz), "gzip")
})

# ---- tar ---------------------------------------------------------------------

test_that("uncompressed POSIX tar header classifies as tar", {
  expect_identical(sniff(make_tar_header()), "tar")
})

test_that("tar magic not at offset 257 does not classify as tar", {
  block <- raw(512L)
  block[1:5] <- charToRaw("ustar")
  # No NUL-free text either, so this falls through to binary (NUL-filled).
  expect_false(identical(sniff(block), "tar"))
})

# ---- xml-urlset --------------------------------------------------------------

test_that("XML urlset classifies as xml-urlset", {
  body <- '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://example.com/</loc></url>
</urlset>'
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

test_that("XML body served as .txt classifies by bytes (feature scenario)", {
  # The file is named sitemap.txt but the BYTES are XML: must be xml-urlset.
  ns <- "http://www.sitemaps.org/schemas/sitemap/0.9"
  body <- paste0(
    "<urlset xmlns=\"", ns, "\">",
    "<url><loc>https://e/</loc></url></urlset>"
  )
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

test_that("namespace-prefixed urlset root is recognised", {
  ns <- "http://www.sitemaps.org/schemas/sitemap/0.9"
  body <- paste0(
    "<sm:urlset xmlns:sm=\"", ns, "\"></sm:urlset>"
  )
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

test_that("BOM-prefixed XML urlset classifies as xml-urlset", {
  bom <- as.raw(c(0xEF, 0xBB, 0xBF))
  body <- as.raw(c(bom, charToRaw('<urlset xmlns="x"><url/></urlset>')))
  expect_identical(sniff(body), "xml-urlset")
})

test_that("UTF-16 BOM-prefixed XML urlset classifies as xml-urlset", {
  bom <- as.raw(c(0xFE, 0xFF))
  body <- as.raw(c(bom, charToRaw("<urlset></urlset>")))
  expect_identical(sniff(body), "xml-urlset")
})

test_that("XML decl plus comment before the root still finds urlset", {
  body <- '<?xml version="1.0"?>
<!-- generated by the build -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>'
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

test_that("urlset behind a DOCTYPE with an internal subset is xml-urlset", {
  # The xxe-attempt.xml shape: the internal subset's ENTITY declaration contains
  # its own ">", so a naive "consume to first >" would strand "]>...<urlset>"
  # and misroute to the text classifier. The bracket-skip must reach the root.
  body <- paste0(
    "<?xml version=\"1.0\"?>",
    "<!DOCTYPE urlset [ <!ENTITY xxe SYSTEM \"file:///etc/hostname\"> ]>",
    "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">",
    "<url><loc>https://example.com/</loc></url></urlset>"
  )
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

test_that("DOCTYPE with no internal subset before urlset still works", {
  body <- paste0(
    "<!DOCTYPE urlset SYSTEM \"sitemap.dtd\">",
    "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"></urlset>"
  )
  expect_identical(sniff(charToRaw(body)), "xml-urlset")
})

# ---- xml-sitemapindex --------------------------------------------------------

test_that("XML sitemapindex classifies as xml-sitemapindex", {
  body <- '<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>https://example.com/sitemap1.xml</loc></sitemap>
</sitemapindex>'
  expect_identical(sniff(charToRaw(body)), "xml-sitemapindex")
})

# ---- feed (RSS / Atom) -------------------------------------------------------

test_that("an RSS root classifies as feed", {
  body <- '<?xml version="1.0"?><rss version="2.0"><channel></channel></rss>'
  expect_identical(sniff(charToRaw(body)), "feed")
})

test_that("an Atom feed root classifies as feed", {
  body <- paste0(
    "<feed xmlns=\"http://www.w3.org/2005/Atom\"><entry/></feed>"
  )
  expect_identical(sniff(charToRaw(body)), "feed")
})

# ---- generic xml -------------------------------------------------------------

test_that("well-formed XML with an unrelated root classifies as xml", {
  body <- '<?xml version="1.0"?><catalog><book/></catalog>'
  expect_identical(sniff(charToRaw(body)), "xml")
})

# ---- html --------------------------------------------------------------------

test_that("DOCTYPE html classifies as html", {
  body <- paste0(
    "<!DOCTYPE html><html><head><title>Hi</title></head>",
    "<body></body></html>"
  )
  expect_identical(sniff(charToRaw(body)), "html")
})

test_that("leading <html> tag classifies as html", {
  body <- "<html lang=\"en\"><body>x</body></html>"
  expect_identical(sniff(charToRaw(body)), "html")
})

test_that("HTML masquerading inside markup is html, not an xml sitemap", {
  # An error page that mentions urlset in text but is really HTML.
  body <- paste0(
    "<!doctype html>\n",
    "<html><body><p>No urlset here, just a 404.</p></body></html>"
  )
  expect_identical(sniff(charToRaw(body)), "html")
})

# ---- text --------------------------------------------------------------------

test_that("plain text list of URLs classifies as text", {
  body <- "https://example.com/a\nhttps://example.com/b\n"
  expect_identical(sniff(charToRaw(body)), "text")
})

test_that("UTF-8 text with high bytes is still text", {
  body <- "café résumé über\n"
  expect_identical(sniff(charToRaw(enc2utf8(body))), "text")
})

# ---- binary ------------------------------------------------------------------

test_that("content with a NUL byte classifies as binary", {
  body <- as.raw(c(charToRaw("PK"), 0x00, 0x03, charToRaw("more")))
  expect_identical(sniff(body), "binary")
})

test_that("dense control bytes (no NUL) classify as binary", {
  ctrl <- as.raw(rep(0x01L, 100L))
  expect_identical(sniff(ctrl), "binary")
})
